# Generated by Django 5.2 on 2025-04-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('printers', '0001_initial'),
        ('tabletypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('copies', models.IntegerField(default=0)),
                ('print', models.BooleanField(default=False)),
                ('commercial_value', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('waiter', models.BooleanField(default=False)),
                ('takeaway', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=False)),
                ('request_price', models.BooleanField(default=False)),
                ('commands', models.BooleanField(default=False)),
                ('surcharge', models.BooleanField(default=False)),
                ('discount', models.BooleanField(default=False)),
                ('vat_included', models.BooleanField(default=False)),
                ('budget', models.BooleanField(default=False)),
                ('cash_only', models.BooleanField(default=False)),
                ('disable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environments.environment')),
                ('printer_commands1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_commands1', to='printers.printer')),
                ('printer_commands2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_commands2', to='printers.printer')),
                ('table_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabletypes.tabletype')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'tables',
                'ordering': ['description'],
            },
        ),
    ]
