# Generated by Django 5.2 on 2025-04-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environment'),
        ),
    ]
