# Generated by Django 5.2 on 2025-04-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('printers', '0001_initial'),
        ('tables', '0002_alter_table_environment'),
        ('tabletypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environments.environment'),
        ),
        migrations.AlterField(
            model_name='table',
            name='printer_commands1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printer_commands1', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='table',
            name='printer_commands2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printer_commands2', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabletypes.tabletype'),
        ),
    ]
