# Generated by Django 5.2 on 2025-04-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_vat_type'),
        ('vatrates', '0002_vatrate_alter_vatrates_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VatRates',
        ),
        migrations.AlterUniqueTogether(
            name='vatrate',
            unique_together={('type', 'start_date')},
        ),
    ]
