# Generated by Django 5.2 on 2025-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_ask_quantity_box_audit_box_change_by_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='copies',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='kitchen_copies',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
