# Generated by Django 5.2 on 2025-04-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_alter_box_copies_alter_box_kitchen_copies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='kitchen_copies',
            new_name='command_copies',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='kitchen_footer',
            new_name='command_footer',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='kitchen_header',
            new_name='command_header',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='kitchen_lines',
            new_name='command_lines',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='group_kitchen_tickets',
            new_name='group_command_tickets',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='print_kitchen_tickets',
            new_name='print_command_tickets',
        ),
    ]
