# Generated by Django 5.2 on 2025-04-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('tables', '0003_alter_table_environment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('orders_only', models.BooleanField(default=False)),
                ('run_file_menu', models.BooleanField(default=False)),
                ('run_config_menu', models.BooleanField(default=False)),
                ('run_reports_menu', models.BooleanField(default=False)),
                ('execute_close', models.BooleanField(default=False)),
                ('print_order', models.BooleanField(default=False)),
                ('reprint_order', models.BooleanField(default=False)),
                ('open_box', models.BooleanField(default=False)),
                ('move_table', models.BooleanField(default=False)),
                ('split_table', models.BooleanField(default=False)),
                ('change_waiter', models.BooleanField(default=False)),
                ('require_waiter_password', models.BooleanField(default=False)),
                ('view_sale', models.BooleanField(default=False)),
                ('invoice_order', models.BooleanField(default=False)),
                ('logout', models.BooleanField(default=False)),
                ('other_options', models.BooleanField(default=False)),
                ('group_row', models.BooleanField(default=False)),
                ('decrease_row', models.BooleanField(default=False)),
                ('repeat_row', models.BooleanField(default=False)),
                ('repeat_last_row', models.BooleanField(default=False)),
                ('delete_row', models.BooleanField(default=False)),
                ('disable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boxes.box')),
                ('default_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tables.table')),
            ],
            options={
                'verbose_name': 'UserGroup',
                'verbose_name_plural': 'UserGroups',
                'db_table': 'usergroups',
            },
        ),
    ]
