# Generated by Django 5.2 on 2025-04-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
