# Generated by Django 5.2 on 2025-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_included', models.BooleanField(null=True)),
                ('uses_commands', models.BooleanField(default=False)),
                ('uses_side_dishes', models.BooleanField(default=False)),
                ('multiple_boxes', models.BooleanField(default=False)),
                ('uses_inventory', models.BooleanField(default=False)),
                ('menu_screens', models.BooleanField(default=False)),
                ('table_time', models.IntegerField(null=True)),
                ('order_time', models.IntegerField(null=True)),
                ('ordered_menu_code', models.BooleanField(default=False)),
                ('local_configuration', models.BooleanField(default=False)),
                ('product_code_button', models.BooleanField(default=False)),
                ('send_commands_escape_takeaway', models.BooleanField(default=False)),
                ('handles_tip', models.BooleanField(default=False)),
                ('waiter_code_button', models.BooleanField(default=False)),
                ('associate_row', models.BooleanField(default=False)),
                ('uses_monitor', models.BooleanField(default=False)),
                ('barcode_character_code', models.CharField(blank=True, max_length=1, null=True)),
                ('uses_keyboard', models.BooleanField(default=False)),
                ('price_button', models.BooleanField(default=False)),
                ('waiter_name_button', models.BooleanField(default=False)),
                ('customer_name_button', models.BooleanField(default=False)),
                ('multiple_prices', models.BooleanField(default=False)),
                ('uses_exchange_rate', models.BooleanField(default=False)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uses_reference_value', models.BooleanField(default=False)),
                ('reference_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_value_rounding', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uses_currency', models.BooleanField(default=False)),
                ('uses_total_rounding', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
