# Generated by Django 5.2 on 2025-04-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemusers', '0001_initial'),
        ('usergroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usergroups.usergroup'),
        ),
    ]
