# Generated by Django 5.2 on 2025-04-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        ('systemusers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boxes.box'),
        ),
    ]
