# Generated by Django 5.2 on 2025-04-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('printers', '0001_initial'),
        ('products', '0001_initial'),
        ('vatrates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printer_commands1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_printer_commands1', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printer_commands2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_printer_commands2', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printer_commands3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_printer_commands3', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printer_commands4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_printer_commands4', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printer_commands5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_printer_commands5', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printer_commands6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_printer_commands6', to='printers.printer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_type', to='vatrates.vatrates'),
        ),
    ]
