# Generated by Django 5.2 on 2025-04-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_group_alter_product_printer_commands1_and_more'),
        ('vatrates', '0002_vatrate_alter_vatrates_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_type', to='vatrates.vatrate'),
        ),
    ]
